### ISSUE TITLE
http://m-css.com not working properly

### ISSUE THREAD

**Issue by pavel06081991** [tivac/modular-css#286] opened 2017-04-29 13:47 UTC
The code from example does not work here http://m-css.com:

```
.red {
    color: red;
}

.blue {
    composes: red;

    background: blue;
}
```

**Comment by TrySound** [comment] 2017-04-29 14:06
@pavel06081991 It works look at the json tab. `composes` way works differently `@extend`.

**Comment by pavel06081991** [comment] 2017-04-29 17:32
@TrySound, look at css tab. The resulted .blur selector does not contain color: blue

**Comment by TrySound** [comment] 2017-04-29 17:35
@tivac As I said `composes` way works differently `@extend`. Properties do not copied or moved. You just has in output two classes. It means that css.blue is equal `blue--hash red--hash`, so both styles are applied.

**Comment by tivac** [comment] 2017-04-30 05:21
@pavel06081991 This is working as intended. I'm going to try and create an example to show you why I'm saying that.

So let's start with the same source CSS you provided.

http://m-css.com/#!/?state=W3sibmFtZSI6IjEuY3NzIiwiY3NzIjoiLnJlZCB7XG4gICAgY29sb3I6IHJlZDtcbn1cblxuLmJsdWUge1xuICAgIGNvbXBvc2VzOiByZWQ7XG5cbiAgICBiYWNrZ3JvdW5kOiBibHVlO1xufSJ9XQ%3D%3D

I pasted the result of that into a JSBin, https://jsbin.com/cazicob/1/edit?html,css,output

You can see that applying the output of `red` to an element applies just the `.red` class (scoped, so that's why the selector changed), but applying the contents of `blue` to an element applies both the `.red` **and** the `.blue` classes.

What `modular-css` does when you use `composes` doesn't rewrite the CSS, it just modifies the output that your JS code sees. The `composes` keyword set up a dependency between them, and now when you take that resulting class string and apply it to an element the properties from both rules apply to the element.

Does that help at all?

**Comment by tivac** [comment] 2017-05-02 06:15
Closing due to lack of a response, feel free to re-open if you have more questions!

**Closed by tivac** 2017-05-02 06:15 UTC
